kind: Service
apiVersion: v1
metadata:
  name: frontend-active
spec:
  selector:
    app: frontend
    deploy-stage: active
  ports:
  - port: 80
    targetPort: service-port
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-active
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend
      deploy-stage: active
  template:
    metadata:
      labels:
        app: frontend
        deploy-stage: active
    spec:
      containers:
      - name: frontend
        image: frontend:v1
        imagePullPolicy: IfNotPresent
        env:
          - name: BACKEND
            value: backend-v1
        ports:
        - name: service-port
          containerPort: 80
